name: Observed matrix

on:
  pull_request:

permissions:
  contents: read

jobs:
  observe:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: esau-morais/observed@73ad0cbdee80d057aa5aa58f25abf04d1f3ab3b2
        with:
          project: .
          base: ${{ github.event.pull_request.base.sha }}
          artifact-name: observed-${{ matrix.os }}
