name: Observed

on:
  pull_request:

permissions:
  contents: read

jobs:
  observe:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: esau-morais/observed@1401e16a8943543c473083da8489a8907cafd680
        with:
          project: .
          base: ${{ github.event.pull_request.base.sha }}
          artifact-name: observed-${{ matrix.os }}
          github-app-client-id: ${{ vars.OBSERVED_APP_CLIENT_ID }}
          github-app-private-key: ${{ secrets.OBSERVED_APP_KEY_NOT_SET }}
